# Generated by Django 5.2.1 on 2025-05-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('number', models.CharField(max_length=16)),
                ('year', models.CharField(max_length=2)),
                ('month', models.CharField(max_length=2)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_transaction', models.DateTimeField()),
                ('from_card', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sent_transactions', to='card.card')),
                ('to_card', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='received_transactions', to='card.card')),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='card.card')),
            ],
        ),
    ]
