# Generated by Django 5.2.1 on 2025-05-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_card_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
