# Generated by Django 5.2.1 on 2025-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_transaction',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
