# Generated by Django 5.2.1 on 2025-05-30 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_transaction_time_transaction'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='token',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='user.token'),
            preserve_default=False,
        ),
    ]
